version: '3.8'

services:
  client:
    build: 
      context: ./client   # Path to the directory containing the client Dockerfile
    ports:
      - "5173:5173"       # Expose port 5173 on the host to port 5173 on the container
    networks:
      - russworldnetwork  # Connect to the custom Docker network

  server:
    build:
      context: ./server   # Path to the directory containing the server Dockerfile
    ports:
      - "6001:6001"       # Expose port 6001 on the host to port 6001 on the container
    networks:
      - russworldnetwork  # Connect to the custom Docker network

networks:
  russworldnetwork: